language: php
sudo: false
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm
install:
  - composer install --prefer-dist
script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/test-reporter
